spring:
  application:
    name: crypto-watcher
  datasource:
    url: jdbc:postgresql://localhost:5432/cryptodb
    username: devuser
    password: devpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  threads:
    virtual:
      enabled: true # Virtual Threads'i burada aktif ediyoruz